export type ProfileType = 
  | 'STRATEGIC_MANAGEMENT'
  | 'SALES'
  | 'FINANCE'
  | 'HUMAN_RESOURCES'
  | 'MARKETING'
  | 'CUSTOMER_SUPPORT'
  | 'PRODUCT_MANAGEMENT'
  | 'RESEARCH_AND_DEVELOPMENT'
  | 'ENGINEERING_FRONTEND'
  | 'ENGINEERING_BACKEND'
  | 'ENGINEERING_MOBILE'
  | 'ENGINEERING_QA'
  | 'ENGINEERING_DEVSECOPS'
  | 'ENGINEERING_RECEPTIONIST'
  | 'ENGINEERING_OFFICE_MANAGER';

export const profiles: ProfileType[] = [
  'STRATEGIC_MANAGEMENT',
  'SALES',
  'FINANCE',
  'HUMAN_RESOURCES',
  'MARKETING',
  'CUSTOMER_SUPPORT',
  'PRODUCT_MANAGEMENT',
  'RESEARCH_AND_DEVELOPMENT',
  'ENGINEERING_FRONTEND',
  'ENGINEERING_BACKEND',
  'ENGINEERING_MOBILE',
  'ENGINEERING_QA',
  'ENGINEERING_DEVSECOPS',
  'ENGINEERING_RECEPTIONIST',
  'ENGINEERING_OFFICE_MANAGER',
];
